# Generated by Django 5.2.10 on 2026-01-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('correo', models.CharField(max_length=40, unique=True)),
                ('telefono', models.CharField(max_length=9, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('rostro_vector', models.JSONField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
